Ability to test request with request options.
BrandEmbassy/mockery-tools pull request #48
Opened 2022-09-01 12:09 UTC by tomasJancar

2022-09-02 07:57 UTC, PetrHeinz requested changes

2022-09-02 07:57 UTC, PetrHeinz commented on src/MockeryTools/Http/HttpClientMockBuilder.php
> +    }
Proč přesouváš konstruktor  níže? Nechceme konstruktory nahoře?

2022-09-02 07:57 UTC, PetrHeinz commented on src/MockeryTools/Http/HttpClientMockBuilder.php
> +    private array $expectedRequestOptions;
Já asi vůbec nevidím, kde to tohle plní něčím jiným jiným, než jen headers...

2022-09-02 07:57 UTC, PetrHeinz commented on src/MockeryTools/Http/HttpClientMockBuilderTest.php
> +                    'timeout' => 2,
Trochu mi tu chybí test case, kdy očekáváš odlišný timout a tak to spadne na nenaplněném očekávání

2022-09-02 07:57 UTC, PetrHeinz commented on src/MockeryTools/Http/HttpRequestOptionsMatcher.php
> +        foreach ($this->expectedRequestOptions[RequestOptions::HEADERS] ?? [] as $headerName => $headerValue) {
Tady to vypadá, že to k matchování používá jen hlavičky...

2022-09-02 09:33 UTC, PetrHeinz approved these changes

2022-09-02 13:07 UTC, PetrHeinz commented on src/MockeryTools/Http/HttpRequestOptionsMatcher.php
> +
Pokud je $optionValue pole, pak musí být i $actual[$optionName] pole. V takovém případě by původní kód spadl na TypeErroru. Navrhuju přidat check:

```suggestion

            if (is_array($optionValue) && !is_array($actual[$optionName])) {
                return false;
            }

```

2022-09-05 07:51 UTC, jakubkulhanek approved these changes

2022-09-05 07:57 UTC, merged